import React from 'react'
import HeroAbout from '@/src/components/HeroAbout'
import BeforeNav from '@/src/components/BeforeNav'
import CenterAbout from '@/src/components/CenterAbout'
import SomeClient from '@/src/components/SomeClient'

import Head from 'next/head'
const aboutus = () => {
  return (
    <div>
      <Head>
        <title>myteam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroAbout />
      <CenterAbout />
      <SomeClient />
      <BeforeNav  />

    </div>
  )
}

export default aboutus
