import React from 'react'
import HeroContact from '@/src/components/HeroContact'
import Head from 'next/head'
const contact = () => {
  return (
    <>
    <Head>
        <title>myteam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroContact />
    </>
  )
}

export default contact
