import React from 'react'
import HeroHome from '@/src/components/HeroHome'
import CenterHome from '@/src/components/CenterHome'
import  Bottom from '@/src/components/Bottom'
import BeforeNav from '@/src/components/BeforeNav'

import Head from 'next/head'
const home = () => {
  return (
    <div className='font-Livvic'>
    <Head>
        <title>myteam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroHome/>
      <CenterHome />
      <Bottom/>
      <BeforeNav/>
      </div>
  )
}

export default home
